apiVersion: locust.io/v1
kind: LocustTest
metadata:
  name: ${SCENARIO}.test
spec:
  image: quay.io/backstage-performance/locust:latest
  imagePullPolicy: Always
  masterCommandSeed: --locustfile /lotest/src/${SCENARIO}.py
    --host ${BASE_HOST}
    --users ${USERS}
    --spawn-rate ${SPAWN_RATE}
    --run-time ${DURATION}
    ${LOCUST_EXTRA_CMD}
  workerCommandSeed: --locustfile /lotest/src/${SCENARIO}.py
    ${LOCUST_EXTRA_CMD}
  workerReplicas: ${WORKERS}
  configMap: locust.${SCENARIO}
