FROM quay.io/vvijayra/python-playwright

# Set environment variable
ENV RHDH_ENDPOINT="https://rhdh-redhat-developer-hub-rhdh-performance.apps.rhperfcluster.ptjz.p1.openshiftapps.com/"

# Set working directory in the container
WORKDIR /app

# Copy the entire project directory into the container
COPY . .FROM quay.io/vvijayra/python-playwright

# Set environment variable
ENV RHDH_ENDPOINT="https://rhdh-redhat-developer-hub-rhdh-performance.apps.rhperfcluster.ptjz.p1.openshiftapps.com/"

# Set working directory in the container
WORKDIR /app

# Copy the entire project directory into the container
COPY . .