global:
  clusterRouterBase: ${OPENSHIFT_APP_DOMAIN}
  imagePullSecrets:
    - rhdh-pull-secret
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
        disabled: true
      # TechDocs
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        disabled: false
orchestrator:
  enabled: false
  sonataflowPlatform:
    externalDBsecretRef: "rhdh-db-credentials"
    externalDBName: "sonataflow"
    externalDBHost: "rhdh-postgresql-cluster-pgbouncer"
    externalDBPort: "5432"
upstream:
  backstage:
    appConfig:
      auth:
        externalAccess:
          - type: legacy
            options:
              secret: ${BACKEND_SECRET}
              subject: legacy-catalog
      backend:
        database:
          connection:
            host: "${POSTGRESQL_HOST}"
            port: "${POSTGRESQL_PORT}"
            user: "${POSTGRESQL_ADMIN_USER}"
            password: "${POSTGRESQL_ADMIN_PASSWORD}"
            ssl:
              rejectUnauthorized: false
            pool:
              min: 1
              max: 2
              acquireTimeoutMillis: 120000
              createTimeoutMillis: 60000
              idleTimeoutMillis: 600000
              reapIntervalMillis: 1000
              createRetryIntervalMillis: 500
          pluginDivisionMode: schema
    containerPorts:
      backend: 7007
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config.rhdh.yaml
    extraEnvVars:
      - name: POSTGRESQL_ADMIN_USER
        valueFrom:
          secretKeyRef:
            name: "rhdh-db-credentials"
            key: "POSTGRES_USER"
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "rhdh-db-credentials"
            key: "POSTGRES_PASSWORD"
      - name: POSTGRESQL_HOST
        valueFrom:
          secretKeyRef:
            name: "rhdh-db-credentials"
            key: "POSTGRES_HOST"
      - name: POSTGRESQL_PORT
        valueFrom:
          secretKeyRef:
            name: "rhdh-db-credentials"
            key: "POSTGRES_PORT"
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: '{{ include "janus-idp.backend-secret-name" $ }}'
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            key: github.token
            name: "{{ .Release.Name }}-plugin-secrets"
      - name: KEYCLOAK_BASE_URL
        value: "https://keycloak-${RHDH_NAMESPACE}.${OPENSHIFT_APP_DOMAIN}"
      - name: KEYCLOAK_LOGIN_REALM
        value: "backstage"
      - name: KEYCLOAK_REALM
        value: "backstage"
      - name: CLIENT_ID
        valueFrom:
          secretKeyRef:
            key: CLIENT_ID
            name: keycloak-client-secret-backstage
      - name: CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            key: CLIENT_SECRET
            name: keycloak-client-secret-backstage
      - name: LOG_LEVEL
        value: "${RHDH_LOG_LEVEL}"
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
    replicas: 1
  postgresql:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: ${RHDH_METRIC}
      path: /metrics
  service:
    ports:
      backend: 7007
      name: http-backend
      targetPort: backend
    type: ClusterIP
