---
extraVolumeMounts:
  - name: rbac-policy
    mountPath: /opt/app-root/src/rbac
  - name: techdocs-data
    mountPath: /opt/app-root/src/techdocs-data
extraVolumes:
  - name: rbac-policy
    persistentVolumeClaim:
      claimName: rbac-policy-pvc
  - name: techdocs-data
    persistentVolumeClaim:
      claimName: rhdh-techdocs
