apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: ${RHDH_NAMESPACE}
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
          key: app-config.rhdh.yaml
        - name: app-config-backend-secret
          key: app-config.rhdh.backend-secret.yaml
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: "dynamic-plugins-rhdh"
    extraFiles:
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        - name: KEYCLOAK_BASE_URL
          value: "https://keycloak-${RHDH_NAMESPACE}.${OPENSHIFT_APP_DOMAIN}"
        - name: KEYCLOAK_LOGIN_REALM
          value: "backstage"
        - name: KEYCLOAK_REALM
          value: "backstage"
        - name: LOG_LEVEL
          value: "${RHDH_LOG_LEVEL}"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: LDAP_TARGET_URL
          value: "ldap://rhdh-ldap:389"
        - name: LDAP_BIND_DN
          value: "cn=admin,dc=test,dc=com"
        - name: LDAP_BIND_SECRET
          value: "admin"
        - name: LDAP_USERS_DN
          value: "ou=users,dc=test,dc=com"
        - name: LDAP_USER_FILTER
          value: "(&(objectClass=inetOrgPerson)(uid=*))"
        - name: LDAP_GROUPS_DN
          value: "ou=groups,dc=test,dc=com"
        - name: LDAP_GROUP_FILTER
          value: "(&(objectClass=groupOfNames)(cn=*))"
      secrets:
        - key: CLIENT_ID
          name: keycloak-client-secret-backstage
        - key: CLIENT_SECRET
          name: keycloak-client-secret-backstage
        - key: BACKEND_SECRET
          name: rhdh-backend-secret
    imagePullSecrets:
      - rhdh-pull-secret
    replicas: ${RHDH_DEPLOYMENT_REPLICAS}
    route:
      enabled: true
  database:
    enableLocalDb: true
