apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: $PG_LABEL
  name: prometheus-$PG_LABEL
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /metrics
  namespaceSelector:
    matchNames:
      - ${RHDH_NAMESPACE}
  selector:
    matchLabels:
      app.kubernetes.io/instance: $PG_LABEL