image:
  repository: "quay.io/backstage-performance/locust-k8s-operator"
  tag: "latest"
  pullPolicy: Always

k8s:
  clusterRole:
    enabled: true

config:
  loadGenerationPods:
    resource:
      cpuRequest: 250m
      memRequest: 256Mi
      ephemeralRequest: 30Mi
      cpuLimit: 250m
      memLimit: 256Mi
      ephemeralLimit: 100Mi
    metricsExporter:
      image: "quay.io/backstage-performance/locust_exporter:latest"
      pullPolicy: Always
