apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage
  labels:
    app: sso
spec:
  client:
    clientId: backstage
    secret: ${KEYCLOAK_CLIENT_SECRET}
    clientAuthenticatorType: client-secret
    defaultClientScopes:
    - profile
    - email
    - roles
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    publicClient: false
    redirectUris:
      - https://${JANUS_HELM_CHART}-developer-hub-${NAMESPACE}.${OPENSHIFT_APP_DOMAIN}/oauth2/callback
    serviceAccountsEnabled: true
    standardFlowEnabled: true
  realmSelector:
    matchLabels:
      app: sso
  serviceAccountClientRoles:
    realm-management:
    - query-groups
    - query-users
    - view-users
