name: PR checks

on:
  pull_request:
    branches:
      - main

env: {}

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run linters
        run: make lint
